[algokit]
min_version = "v2.0.0"

[project]
type = 'workspace'
projects_root_path = 'projects'

[project.run]
build = [
  'new-algobounty-contract',
  'new-algobounty-frontend',
  'new-algobounty-backend',
]
